"""
sql_validator.py

Validates SQL generated by the LLM.
"""

import re


class SQLValidator:

    # Keywords that are NOT allowed
    FORBIDDEN_KEYWORDS = [
        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "ALTER",
        "CREATE",
        "TRUNCATE",
        "MERGE",
        "CALL",
        "COPY",
        "ATTACH",
        "DETACH",
        "PRAGMA",
    ]

    @staticmethod
    def validate(sql: str) -> str:
        """
        Validate generated SQL.

        Returns:
            Clean SQL

        Raises:
            ValueError if SQL is unsafe.
        """

        # Remove markdown
        sql = sql.replace("```sql", "")
        sql = sql.replace("```", "")
        sql = sql.strip()

        # Must start with SELECT or WITH
        if not sql.upper().startswith(("SELECT", "WITH")):
            raise ValueError("Only SELECT queries are allowed.")

        # Reject forbidden keywords
        upper_sql = sql.upper()

        for keyword in SQLValidator.FORBIDDEN_KEYWORDS:
            if re.search(rf"\b{keyword}\b", upper_sql):
                raise ValueError(f"Unsafe SQL detected: {keyword}")

        # Only one statement allowed
        sql = sql.rstrip(";")

        if ";" in sql:
            raise ValueError("Multiple SQL statements are not allowed.")

        return sql